version: '3'
services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - DB_CONNECT=mongodb+srv://automobileabout:39hZb4CfTbzpNbAl@cluster0.flrukwy.mongodb.net/ # Use the MongoDB service name
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
